name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'Plant-Kennel'
        reponame: 'Plant-Kennel.github.io' # nothing I put here is found in my Github PR build Vue check
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
  debug:
    runs-on: ubuntu-latest
    name: Print repository name
    steps:
      - run: echo "Repository name ${{ github.event.repository.name }}"
